### ISSUE TITLE
Error: Missing value auth-url required for auth plugin password

### ISSUE THREAD

**Issue by LI-explorer** [CornellCAC/slurm-cluster-in-openstack#1]
Hi,

We are trying to follow the instruction to Install Ansible. And when we want to confirm access by using the **openstack project list** command, we got the error **Missing value auth-url required for auth plugin password**. Could you give us any suggestions on it? 

Thank you.

**Comment by shl1** [comment]
Hi,

That means you do not have access to your openstack cloud. Did you remember to source in your cloud credentials? https://docs.openstack.org/newton/user-guide/common/cli-set-environment-variables-using-openstack-rc.html


Steven Lee
Cornell University Center for Advanced Computing
721 Rhodes Hall, Ithaca NY 14853
Office: 607-255-2843
Email: ***@***.***
